### ISSUE TITLE
Scoreboard doesn't update properly

### ISSUE THREAD

**Issue by kerbybit** [ChatTriggers/ChatTriggers#90] opened 2018-03-03 19:46 UTC
the Scoreboard wrapper was not properly implemented and never updates its values

**Comment by FalseHonesty** [comment] 2018-03-03 20:06
Is clearcache ever called?

**Comment by kerbybit** [comment] 2018-03-03 20:07
probably not. I still blame cham

**Comment by qkleinfelter** [comment] 2018-03-05 14:53
This worked when we had MinecraftVars because I always called clearcache before the var was reassigned (in providedlibs), so I blame whoever removed MCVars

**Comment by FalseHonesty** [comment] 2018-03-08 00:00
Confirmed fixed as of commit cd8613e59fc8958c64b8e3f8778ed3be0e8d4cfe

**Closed as completed by FalseHonesty** 2018-03-08 00:00 UTC
Labels: bug
